[workspace]
members = ["diy-os", "diy-os-lib", "diy-os-macros", "kernel_logger", "runners", "spinlock", "drivers/primitive_memmapped_fat32_read_only_driver"]
resolver = "3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
