name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./diy-os
    steps:
    - uses: actions/checkout@v4
    - name: Install Miri
      run: |
          rustup toolchain install nightly --component miri rust-src
          rustup override set nightly
          cargo miri setup
    - name: Build
      run: cargo build --verbose --lib
    - name: Run tests
      run: cargo test --verbose --lib
